version: '3.8'

services:
  web-1:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT_APP=8080
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - red-app
    restart: always
    depends_on:
      - database

  web-2:
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - PORT_APP=8081
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - red-app
    restart: always
    depends_on:
      - database

  web-3:
    build: .
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - PORT_APP=8082
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - red-app
    restart: always
    depends_on:
      - database

  database:
    image: mysql:latest
    env_file:
      - .env
    ports:
        - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    networks:
      - red-app

  phpmyadmin:
    image: phpmyadmin:5.1.1
    env_file:
      - .env
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - red-app
    depends_on:
      - database

networks:
  red-app: